<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SimpleStockFlow.Adapters.Security</RootNamespace>
    <AssemblyName>SimpleStockFlow.Adapters.Security</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.1.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../application/SimpleStockFlow.Application.csproj" />
  </ItemGroup>
</Project>
